add_prepaid_credit:
  fields:
    entry_id:
      required: true
      selector:
        text:
    amount:
      required: true
      selector:
        number:
          min: 0
          step: 0.01
          mode: box

set_prepaid_balance:
  fields:
    entry_id:
      required: true
      selector:
        text:
    amount:
      required: true
      selector:
        number:
          min: 0
          step: 0.01
          mode: box

reset_billing_cycle:
  fields:
    entry_id:
      required: true
      selector:
        text:
